[package]
name = "casecsv"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2.2"
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.16.1", features = ["derive"] }
derive_builder = "0.12"
zip = "0.6.6"

[dev-dependencies]
anyhow = "1"
