[package]
name = "casecsv"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2.2"
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.16.1", features = ["derive"] }
zip = "0.6.6"